version: '3.9'

services:
  django_project:
    container_name: django_project
    build:
      context: .
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A AvitoStats worker -l info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  flower:
    build: .
    command: celery -A AvitoStats flower
    ports:
      - "5555:5555"
    depends_on:
      - celery
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery_beat:
    build: .
    command: celery -A AvitoStats beat -l info -S django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - celery
      - redis
    environment:
      - CELERY_BEAT_SCHEDULER=django_celery_beat.schedulers:DatabaseScheduler

volumes:
  pg_data: