# Generated by Django 5.1.5 on 2025-01-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParserCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_region_id', models.CharField(max_length=200, verbose_name='pr_id')),
                ('phrase', models.CharField(max_length=200, verbose_name='phrase')),
                ('region', models.CharField(max_length=200, verbose_name='region')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ParserCall',
                'verbose_name_plural': 'ParserCalls',
            },
        ),
    ]
