# Generated by Django 5.1.5 on 2025-01-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsercall',
            name='number_of_ads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
