# Generated by Django 5.1.5 on 2025-01-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_parsercall_number_of_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsercall',
            name='number_of_ads',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
